from __future__ import annotations

import re
from typing import Iterable, List

STOPWORDS_PT = {
    "a",
    "à",
    "ao",
    "aos",
    "as",
    "o",
    "os",
    "um",
    "uma",
    "uns",
    "umas",
    "de",
    "do",
    "da",
    "dos",
    "das",
    "em",
    "no",
    "na",
    "nos",
    "nas",
    "por",
    "para",
    "com",
    "sem",
    "sob",
    "sobre",
    "entre",
    "até",
    "apos",
    "após",
    "ante",
    "perante",
    "contra",
    "desde",
    "que",
    "e",
    "ou",
    "mas",
    "se",
    "porque",
    "quando",
    "como",
    "onde",
    "quanto",
    "qual",
    "quais",
    "quem",
    "cujo",
    "cuja",
    "isso",
    "isto",
    "aquilo",
    "este",
    "esta",
    "estes",
    "estas",
    "esse",
    "essa",
    "esses",
    "essas",
    "aquele",
    "aquela",
    "aqueles",
    "aquelas",
    "me",
    "te",
    "se",
    "lhe",
    "lhes",
    "nos",
    "vos",
    "minha",
    "meu",
    "meus",
    "minhas",
    "sua",
    "seu",
    "seus",
    "suas",
    "nossa",
    "nosso",
    "nossos",
    "nossas",
    "você",
    "voce",
    "vocês",
    "voces",
    "eu",
    "tu",
    "ele",
    "ela",
    "eles",
    "elas",
    "a",
    "gente",
    "ser",
    "estar",
    "ter",
    "haver",
    "foi",
    "era",
    "são",
    "sao",
    "está",
    "esta",
    "estão",
    "estao",
    "estava",
    "estavam",
    "tem",
    "têm",
    "tinha",
    "tiveram",
    "vai",
    "vão",
    "vao",
    "fui",
    "somos",
    "sou",
    "é",
    "nao",
    "não",
    "sim",
    "mais",
    "menos",
    "muito",
    "muita",
    "muitos",
    "muitas",
    "já",
    "ja",
    "ainda",
    "também",
    "tambem",
    "só",
    "so",
    "aqui",
    "ali",
    "lá",
    "la",
    "aí",
    "ai",
    "hoje",
    "ontem",
    "amanhã",
    "amanha",
    "agora",
    "depois",
    "antes",
    "pois",
    "então",
    "entao",
    "além",
    "alem",
    "tudo",
    "toda",
    "todo",
    "todos",
    "todas",
    "cada",
    "qualquer",
    "nenhum",
    "nenhuma",
}

_TOKEN_RE = re.compile(r"[A-Za-zÀ-ÿ0-9]+", re.UNICODE)

try:
    import snowballstemmer

    _STEMMER = snowballstemmer.stemmer("portuguese")
except Exception:
    _STEMMER = None


def tokenize(text: str) -> List[str]:
    return [token.lower() for token in _TOKEN_RE.findall(text)]


def remove_stopwords(tokens: Iterable[str]) -> List[str]:
    return [token for token in tokens if token and token not in STOPWORDS_PT]


def _simple_stem(token: str) -> str:
    for suffix in (
        "mente",
        "ções",
        "ção",
        "sões",
        "são",
        "idades",
        "idade",
        "amentos",
        "amento",
        "áveis",
        "ável",
        "mente",
        "adoras",
        "adores",
        "adora",
        "ador",
        "açoes",
        "acao",
        "adas",
        "ados",
        "ando",
        "endo",
        "indo",
        "ezas",
        "eza",
        "icos",
        "icas",
        "ico",
        "ica",
        "ções",
    ):
        if token.endswith(suffix) and len(token) > len(suffix) + 2:
            return token[: -len(suffix)]
    return token


def stem_words(tokens: Iterable[str]) -> List[str]:
    token_list = list(tokens)
    if _STEMMER:
        return _STEMMER.stemWords(token_list)
    return [_simple_stem(token) for token in token_list]


def preprocess_text(text: str) -> List[str]:
    tokens = tokenize(text)
    tokens = remove_stopwords(tokens)
    return stem_words(tokens)
